### ISSUE TITLE
Implement "DELETE /objects/{object_id}/access/{access_id}"

### ISSUE THREAD

**Issue by uniqueg** [elixir-cloud-aai/drs-filer#27]
### Description

As in issue #10 and PR #9, but for deleting an access method rather than an object. Note that at least one access method always has to be available for a given object.

### Proposed solution

- Add an endpoint `DELETE /objects/{object_id}/access/{access_id}` to the custom [DRS-Filer specification](https://github.com/elixir-cloud-aai/drs-filer/blob/8cc77d360a0d25e164a63feabf7b5bbdc90a6236/drs_filer/api/additional.data_repository_service.swagger.yaml#L76).
- Implement the controller for the new endpoint
- Ensure that the last available access method cannot be deleted (issue a `400/BadRequest` response if attempted to)
- Add/update unit tests

Compare the [`DELETE /tools/{id}/versions/{version_id}` controller](https://github.com/elixir-cloud-aai/trs-filer/blob/2158df4f2a8bd6850d0a9fc20a13dd6ad205e276/trs_filer/ga4gh/trs/server.py#L610) for an example on how to make sure that the last list item (here: a tool version) cannot be deleted.

**Comment by chinvib66** [comment]
@uniqueg I would like to take up this issue.

**Comment by uniqueg** [comment]
That's awesome, @chinvib66, you are very welcome to do so!
