### ISSUE TITLE
Implement "GET /service-info"

### ISSUE THREAD

**Issue by uniqueg** [elixir-cloud-aai/drs-filer#28]
### Description

GA4GH API services should come with a service info endpoint that provides essential information required for service discovery and effective usage. Previously, the definition for a service info endpoint was part of each individual API specification. Recently, however, the service info endpoint specification was harmonized and [externalized](https://github.com/ga4gh-discovery/ga4gh-service-info/blob/develop/service-info.yaml).

### Proposed change

- [ ] Add the [latest specification](https://github.com/ga4gh-discovery/ga4gh-service-info/blob/daa4014a27545376415882a1ef17cf9fc4ae6a05/service-info.yaml) for `GET /service-info` to the repository and include it in the app configuration; ensure that it is added in an order that ensure that the resulting Swagger UI will have the DRS service description - not the service info one
- [ ] Add a dedicated database collection and default service info parameters to the app config, and add the necessary logic to populate the service info once the app starts; see https://github.com/elixir-cloud-aai/trs-filer/pull/40 in the [TRS-Filer](https://github.com/elixir-cloud-aai/trs-filer) repository to find out what changes are required; note that the PR also includes a `POST /service-info` endpoint, which is listed as a separate issue here (see #29)
- [ ] Implement a controller for `GET /service-info`
- [ ] Add/modify the necessary tests

**Comment by sarthakgupta072** [comment]
Hey @uniqueg. 

The latest specification given [here](https://github.com/ga4gh-discovery/ga4gh-service-info/blob/develop/service-info.yaml) is in OpenAPI 3.0, but `drs-filer` uses OpenAPI 2.0.

Should I convert it and make a separate file (as done in trs-filer), and give it the name -  `20200131.11d2c12.service-info.yaml`?

Asking this as I am not using the exact file as it is, but converting it to OpenAPI 2.0 specification.

Please Advice :)
