### ISSUE TITLE
Unable to launch the latest version from GitHub w/ ImportError: cannot import name 'foca' from 'foca.foca'

### ISSUE THREAD

**Issue by superbsky** [elixir-cloud-aai/drs-filer#44]
Describe the bug
Unable to launch the latest version from GitHub w/ ImportError: cannot import name 'foca' from 'foca.foca'

To Reproduce

git clone https://github.com/elixir-cloud-aai/drs-filer
docker-compose up -d --build
docker-compose ps
       Name                      Command                 State                         Ports                    
----------------------------------------------------------------------------------------------------------------
drs-filer_drs_1       bash -c cd /app/drs_filer; ...   Restarting                                               
drs-filer_mongodb_1   docker-entrypoint.sh mongod      Up           0.0.0.0:27017->27017/tcp,:::27017->27017/tcp

Expected behavior
Successfully launched service listening on 8080

Software
uname -a
Linux 5.13.0-1031-azure https://github.com/elixir-cloud-aai/cwl-WES/pull/37~20.04.1-Ubuntu SMP Mon Jun 13 22:51:01 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

docker-compose --version
docker-compose version 1.25.0, build unknown

Additional context
drs_1      | Traceback (most recent call last):
drs_1      |   File "/app/drs_filer/app.py", line 5, in <module>
drs_1      |     from foca.foca import foca
drs_1      | ImportError: cannot import name 'foca' from 'foca.foca' (/usr/local/lib/python3.10/site-packages/foca/foca.py)
drs_1      | Traceback (most recent call last):
drs_1      |   File "/app/drs_filer/app.py", line 5, in <module>
drs_1      |     from foca.foca import foca
drs_1      | ImportError: cannot import name 'foca' from 'foca.foca' (/usr/local/lib/python3.10/site-packages/foca/foca.py)
drs_1      | Traceback (most recent call last):
drs_1      |   File "/app/drs_filer/app.py", line 5, in <module>
drs_1      |     from foca.foca import foca
drs_1      | ImportError: cannot import name 'foca' from 'foca.foca' (/usr/local/lib/python3.10/site-packages/foca/foca.py)
drs_1      | Traceback (most recent call last):
drs_1      |   File "/app/drs_filer/app.py", line 5, in <module>
drs_1      |     from foca.foca import foca
drs_1      | ImportError: cannot import name 'foca' from 'foca.foca' (/usr/local/lib/python3.10/site-packages/foca/foca.py)
drs_1      | Traceback (most recent call last):
drs_1      |   File "/app/drs_filer/app.py", line 5, in <module>
drs_1      |     from foca.foca import foca
drs_1      | ImportError: cannot import name 'foca' from 'foca.foca' (/usr/local/lib/python3.10/site-packages/foca/foca.py)
drs_1      | Traceback (most recent call last):
drs_1      |   File "/app/drs_filer/app.py", line 5, in <module>
drs_1      |     from foca.foca import foca
drs_1      | ImportError: cannot import name 'foca' from 'foca.foca' (/usr/local/lib/python3.10/site-packages/foca/foca.py)
drs_1      | Traceback (most recent call last):
drs_1      |   File "/app/drs_filer/app.py", line 5, in <module>
drs_1      |     from foca.foca import foca
drs_1      | ImportError: cannot import name 'foca' from 'foca.foca' (/usr/local/lib/python3.10/site-packages/foca/foca.py)

**Comment by uniqueg** [comment]
Thanks for the nice bug report, @superbsky. I think the issue should be fixed now.
