### ISSUE TITLE
Delete endpoint not working

### ISSUE THREAD

**Issue by psankhe28** [elixir-cloud-aai/drs-filer#53]
The endpoint to delete an access method of an object with specific object id and access id is not working: `http://localhost:8080/ga4gh/drs/v1/objects/{object_id}/access/{access_id}`

![image](https://github.com/elixir-cloud-aai/drs-filer/assets/84843461/9b00ed4e-f14d-46ca-8fb9-772cd9a76ad4)

**Comment by kushagra189** [comment]
Did you check the logs? What was the issue and why was it saying request as malformed?
IMO is should have something to do with the request and should not ideally be an issue from functional perspective.

**Comment by psankhe28** [comment]
ERROR: Will not delete only remaining access method for object: Av~oBb [ga4gh.drs.server]
This is the error I get on trying to delete the access method. 
Maybe we need to make changes to the error response so that the user can understand what went wrong

**Comment by uniqueg** [comment]
Yes, it seems the operation is working fine (it should _not_ accept to delete the last access method), it's just the error message is misleading.

So we should create a custom error, e.g., `DeletionDeniedError` [here](https://github.com/elixir-cloud-aai/drs-filer/blob/a93caebf84fa295c06e105f0005016e18ae9641e/drs_filer/errors/exceptions.py) and add it to the `exceptions` dictionary (in the same module) with a reasonable error message (and probably a different status than `400`, probably `409`). We should then raise that custom error in the code [here](https://github.com/elixir-cloud-aai/drs-filer/blob/a93caebf84fa295c06e105f0005016e18ae9641e/drs_filer/ga4gh/drs/server.py#L156) (and probably also add the 409 response to the [specs](https://github.com/elixir-cloud-aai/drs-filer/blob/a93caebf84fa295c06e105f0005016e18ae9641e/drs_filer/api/additional.data_repository_service.swagger.yaml)).
