### ISSUE TITLE
Replace code that has been moved to archetype

### ISSUE THREAD

**Issue by sarthakgupta072** [elixir-cloud-aai/drs-filer#6]
A lot of the code shared between this service and related services [proTES](https://github.com/elixir-cloud-aai/proTES), [proWES](https://github.com/elixir-cloud-aai/proWES) and to some extent [TEStribute](https://github.com/elixir-cloud-aai/TEStribute), [mock-DRS](https://github.com/elixir-cloud-aai/mock-DRS) and [mock-TES](https://github.com/elixir-cloud-aai/mock-TES), is successively being moved to the archetype library [FOCA](https://github.com/elixir-cloud-aai/foca).

Duplicate code should now successively be removed from this service. This meta issue should document the progress of this process and remain open. Please open a separate issue for the replacement of every individual module (or other unit of code, as appropriate) and link to this issue.

**Comment by uniqueg** [comment]
Guess we're making full use of FOCA now, so I will close this, too
