### ISSUE TITLE
Implement POST endpoint

### ISSUE THREAD

**Issue by sarthakgupta072** [elixir-cloud-aai/drs-filer#8]
Design and implement the POST endpoint to register meta-data in drs-filer.

Design doc: https://docs.google.com/document/d/1yNaL_XClDkcqJ9npm3uYX_66fmRsH9GvhhXlKW_eIOI/edit?usp=sharing

**Comment by uniqueg** [comment]
Note from a [previous discussion](https://github.com/elixir-cloud-aai/drs-filer/pull/5#discussion_r457171503_) in #5 that some parameters are _not_ set by the user, but by the implementation. This includes identifiers, e.g.:
- `object_id`
- `self_uri`

See DRS specification for details.

@sarthakgupta072: Could you please prepare a list of all properties that either of the `GET` endpoints in the DRS specs request? We can then decide which ones are to be provided by the user in the `POST` endpoint when registering data and which ones are to be generated by the implementation. Please add it as a comment to this issue and not to the design doc.

**Comment by sarthakgupta072** [comment]
The specs of data repository service schema have been specified here: https://github.com/ga4gh/data-repository-service-schemas/blob/master/openapi/data_repository_service.swagger.yaml

For `GET` endpoints, there are the properties that are included. The properties in **bold** are required properties:

| Definition     | Type   | Property: type                                                                                                                                                                                                                                                                                                                                                                                                    |
|----------------|--------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| DrsObject      | object | **id**: string <br>name: string<br>**self_uri**: string<br>**size**: integer (format: int64)<br>**created_time**: string (format: date-time)<br>updated_time: string (format: date-time)<br>version: string<br>mime_type: string<br>**checksums**: array (items: Checksum)<br>access_methods: array (items: AccessMethod)<br>contents: array (items: ContentsObject)<br>description: string<br>aliases: array(items: string) |
| Checksum       | object | **checksum**: string<br>**type**: string                                                                                                                                                                                                                                                                                                                                                                              |
| AccessMethod   | object | **type**: string<br>access_url: AccessURL<br>access_id: string<br>region: string                                                                                                                                                                                                                                                                                                                                    |
| AccessURL      | object | **url**: string<br>headers: array (items: string)                                                                                                                                                                                                                                                                                                                                                                   |
| ContentsObject | object | **name**: string<br>id: string<br>drs_uri: array (items: string)<br>contents: array (items: ContentsObject)                                                                                                                                                                                                                                                                                                         |
